# Generated by Django 4.0.6 on 2022-08-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=64)),
                ('stock', models.IntegerField()),
                ('daily_ratings', models.FloatField()),
            ],
        ),
    ]
